on:
  push:
    branches: [ master ]

name: Deploy

jobs:
  deploy-postgre:
    name: Deploy Postgre
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Mongo
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          source: "./mongo/docker-compose.yml"
          target: /home/${{ secrets.REMOTE_USER }}/app/mongo
          strip_components: 1

      - name: Rollout Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            sudo docker-compose -f /home/${{ secrets.REMOTE_USER }}/app/mongo/docker-compose.yml up -d
  deploy-mongo:
    name: Deploy Redis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Manifest
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          source: "./redis/docker-compose.yml"
          target: /home/${{ secrets.REMOTE_USER }}/app/redis
          strip_components: 1

      - name: Rollout Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            sudo docker-compose -f /home/${{ secrets.REMOTE_USER }}/app/redis/docker-compose.yml up -d
  deploy-redis:
    name: Deploy Postgres
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy Manifest
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          source: "./postgres/docker-compose.yml"
          target: /home/${{ secrets.REMOTE_USER }}/app/postgres
          strip_components: 1

      - name: Rollout Application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.REMOTE_PASSWORD }}
          port: 22
          script: |
            sudo docker-compose -f /home/${{ secrets.REMOTE_USER }}/app/postgres/docker-compose.yml up -d